### ISSUE TITLE
Add fabric api dependency

### ISSUE THREAD

**Issue by pavog** [tr7zw/MiniMePets#1]
When I start this mod without the fabric api mod https://www.curseforge.com/minecraft/mc-mods/fabric-api installed, it throws an error telling me to install the fabric api.

Could you please add the fabric api to the dependencies of the fabric version of the mod?

**Comment by tr7zw** [comment]
Yea I can do that, but all Fabric installs should have Fabric API auto installed(you will need it anyway)?

**Comment by pavog** [comment]
Would be useful, yeah.
I install my mods manually and I did not see any dependencies.
So I thought that I can simply drop the mod into my mods folder and it should be good to go.

**Comment by tr7zw** [comment]
> So I thought that I can simply drop the mod into my mods folder and it should be good to go.

I mean it is exactly like that. Most mods won't run without Fabric API, so I don't really consider it a "noteworthy dependency"(unlike for example requiring cloth-config). If you want to configure the settings of the mod you require ModMenu, which also requires the FabricAPI. I think actually most of my mods don't explicitly state the FabricAPI as dependency.

**Comment by pavog** [comment]
I mean, it's just a jar that you have to download and put in the mods folder, but it's still a dependency imho, because it is still a software that you have to install.

**Comment by tr7zw** [comment]
Has been corrected for 1.20.2+.
