### ISSUE TITLE
Add more Versions!

### ISSUE THREAD

**Issue by TrexTheDino** [tr7zw/MiniMePets#6]
I am using Fabric 1.19.4 but I need this mod!
Please make this mod in 1.19.4 also!

**Comment by tr7zw** [comment]
Just try the 1.19.2 release on 1.19.4. I don't recall rather I tested that, but should work I guess(or at least no one reported that it didn't).

**Comment by TrexTheDino** [comment]
> Just try the 1.19.2 release on 1.19.4. I don't recall rather I tested that, but should work I guess(or at least no one reported that it didn't).

Not working :(   I think it needs something to change. Can u ?
Please add it into 1.19.4 :)

My game crashing when I give name to my dog!
And its not Working in 1.19.4 :(
Everytime I open that world my game got crashed.
After deleting mod my world is working fine.
But I need this mod.
Please help me!

**Comment by floofyneko69** [comment]
Ah, since this hasn't closed, I also came to post an issue about the latest release, 1.20.1
It surprisingly shows up on Mod Menu, but doesn't work in game, and since 1.20.4 has been released for about 3 months now, I hope to know if there's underlying issues updating to 1.20.4, or if 1.20.1 is supposed to work for later versions.

**Comment by tr7zw** [comment]
> Ah, since this hasn't closed, I also came to post an issue about the latest release, 1.20.1 It surprisingly shows up on Mod Menu, but doesn't work in game, and since 1.20.4 has been released for about 3 months now, I hope to know if there's underlying issues updating to 1.20.4, or if 1.20.1 is supposed to work for later versions.

I created the 1.20.2/1.20.4 versions last night. Download them from the actions tab above.

**Comment by tr7zw** [comment]
Welp build failed, need to fix it first

**Comment by tr7zw** [comment]
Pushing out the release now.
