### ISSUE TITLE
[Forge] events not fired when rendering as player

### ISSUE THREAD

**Issue by Mrbysco** [tr7zw/MiniMePets#7]
Currently, when MiniMePets renders wolves/cats as players, the `RenderLivingEvent` sub-events are not being triggered. This poses an issue for mods like mine, Notable Bubble Text, which relies on `RenderLivingEvent.Post` to render text bubbles above mobs' heads when specific NBT conditions are met.

I was wondering if it would be possible to implement support for `RenderLivingEvent` in the context of tamed wolves and cats in MiniMePets.

**Comment by generikb** [comment]
Yo!
Just to add a little insight...I use MiniMePets in my Twitch Streams to have some of my subscribers follow me around in-game! I love the mod, it's super fun!

MrBysco has recently release Notable Bubble Text, which allows you to have mobs "talk" via little cartoon speech bubbles.  I've set it up where my subscribers can chat with me in-game this way!  However, it's not compatible with MiniMePets for the reasons MrBysco listed above.

Would *really* love it if this could be compatible, thank you in advance for your help!

**Comment by tr7zw** [comment]
UHHH possible that I cancel the vanilla rendering too early, causing that event to get skipped(as I don't use the Forge API since I mainly code for Fabric, making the mod better portable between loaders). I guess the simplest way would be to pass that render call to the forge-specific side of the mod, and manually trigger the RenderLivingEvent from there. I'm currently rather busy in the last 2 weeks of my bachelor thesis, so either create a PR to add that event quickly, or wait till I'm done and get around to updating my mods for 1.20.3, where I'll be able to quickly add this in the recent-ish versions.

**Comment by tr7zw** [comment]
Oh wait, generikb. Then I'll make an exception and try to get this fixed before going to bed and continuing to write tomorrow. As I said, hopefully, it's nothing too complicated.

**Comment by generikb** [comment]
Oh man, that would be really fantastic! I appreciate it very much.  If you have time over the weekends, hop by the stream and I'll show ya what we've done with your mod!

**Comment by tr7zw** [comment]
![grafik](https://github.com/tr7zw/MiniMePets/assets/5133936/b271d7a9-3bc6-4a46-886f-00eebf6472ad)
I think I got it fixed. Will have to backport it from 1.20.1 to I assume 1.19.2(judging from the streams saying 1.19 and the mod being 1.19.2)?

**Comment by generikb** [comment]
nice! look at that!  Yeah I use it right now for 1.19.2, next modpack will be 1.120.1 but that'll be a ways off.  Thank you so much!!!

**Comment by tr7zw** [comment]
Right now fighting with the deploy. I'll be honest, this mod is kinda of one of the forgotten ones of mine, so the automated deployment just managed to release the file on the wrong mod page(https://legacy.curseforge.com/minecraft/mc-mods/disguiseheads), Modrinth doesn't have a page in the first place, and I apparently never made a 1.20.2 or 1.19.3/4 version. Guess lots of stuff to fix for when I'm done with my thesis. But 1.19.2 Forge is now up https://legacy.curseforge.com/minecraft/mc-mods/minimepets/files/4910225 over at curseforge.

**Comment by tr7zw** [comment]
The classic problem. "Should be a quick fix", yet takes 1 hour to implement and release properly for 2 mc versions. 
> If you have time over the weekends, hop by the stream and I'll show ya what we've done with your mod!

Sure, I'll try to catch the next stream, tho I'm not much of a Twitch person, so will have to rely on my phone notifying me.

**Comment by tr7zw** [comment]
@Mrbysco Also fyi, you seem to have some sorting issues in the rendering.
![grafik](https://github.com/tr7zw/MiniMePets/assets/5133936/8a2988c4-b62c-4918-9fd4-4a5f7d2cc5ff)
![grafik](https://github.com/tr7zw/MiniMePets/assets/5133936/0cafb88a-6064-446c-a013-2cec9fa63f32)
The parrot in the background can be rendered after the speech bubble, getting sandwiched between the text and the bubble. You might want to move the rendering to he bubbles to past the entity rendering or look into what's up with the depth buffer.
![grafik](https://github.com/tr7zw/MiniMePets/assets/5133936/da244cbe-e290-4e00-9efa-880fe84b04be)

**Comment by Mrbysco** [comment]
I've already pushed a commit that fixes some rendering issues, no clue if it fixes that 🤷

**Comment by generikb** [comment]
![image](https://github.com/tr7zw/MiniMePets/assets/41623747/d3e90046-b5df-4937-8e6f-53aa9bda3661)

downloaded and confirmed working!!! Thank you so much!
